Pushup/urls.py
from django.urls import path
from . import views

app_name = 'pushup'

urlpatterns = [
    path('',views.home_view,name='home'),
    path('home/',views.home_view,name='home'),
    path('add_pushup/',views.add_push_up,name='add_pushup'),
    path('stats/',views.stats_view,name='stats'),
]

User/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as v
from .forms import UserLoginForm

app_name='user'

urlpatterns = [
    path('register/',views.sign_up,name='register'),
    path('login/',v.LoginView.as_view(template_name="registration/login.html",authentication_form=UserLoginForm),
         name = 'login'),
]

pompki/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('User.urls',namespace='user')),
    path('',include('Pushup.urls',namespace='pushup')),
    path('',include('django.contrib.auth.urls')),
]

Pushup/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MinValueValidator,MaxValueValidator
from datetime import date,timedelta

class PushUpDay(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    day = models.DateField(default= timezone.now())
    count = models.IntegerField(null=False,validators=[
        MinValueValidator(1),
        MaxValueValidator(10000)
    ])

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=False)
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    age = models.IntegerField(null=True)

def top5_this_week():
    class pushup:
        def __init__(self,user):
            self.user=user
        total_count = 0
    users= User.objects.all()
    pushups_obj = []
    for user in users:
        pushups_obj.append(pushup(user))
    pushups = PushUpDay.objects.filter(day__gte=date.today() - timedelta(days=7))
    for pushup in pushups_obj:
        for p in pushups:
            if pushup.user == p.user:
                pushup.total_count+=p.count
    return sorted(pushups_obj,reverse=True,key=lambda x:x.total_count)[:5]

def top3_this_month():
    class seria:
        def __init__(self,user):
            self.user = user
        series = 0

    users = User.objects.all()
    series_obj = []
    for user in users:
        series_obj.append(seria(user))
    pushups = PushUpDay.objects.filter(day__gte=date.today()-timedelta(days=30))
    for series in series_obj:
        for p in pushups:
            if series.user == p.user:
                series.series+=1
    return sorted(series_obj,reverse=True,key=lambda x:x.series)[:3]

User/models.py
from django.db import models

# Create your models here.

Pushup/forms.py
from django import forms
import datetime
from .models import PushUpDay

class AddPushup(forms.ModelForm):
    class Meta:
        model = PushUpDay
        fields = ['count']
        labels = {
            'count':'Ilość pompek'
        }

    def clean(self):
        pass

User/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator,MaxValueValidator

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Nazwa użytkownika')
    password = forms.CharField(label ='Hasło',widget=forms.PasswordInput())

class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=30,required=True,label = "Nazwa użytkownika/pseudonim")
    name = forms.CharField(max_length=30,required=True,label='Imię')
    surname = forms.CharField(max_length=30,required=True,label='Nazwisko')
    age = forms.IntegerField(required=True,validators=[
        MinValueValidator(10),
        MaxValueValidator(90)
    ])
    password1 = forms.CharField(label='Hasło',strip=False,widget=forms.PasswordInput())
    password2 = forms.CharField(label='Potwierdź hasło',strip=False,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ["username",'name','surname','age',"password1","password2"]

Pushup/views.py
from django.shortcuts import render
from .forms import AddPushup
from .models import PushUpDay,top5_this_week,top3_this_month
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone



def home_view(request):
    return render(request,'home.html',{})

@login_required(login_url='/login')
def add_push_up(request):
    push_ups = PushUpDay.objects.filter(user=request.user,day=timezone.now())
    if push_ups:
        msg = 'Dzisiaj już dodałeś pompki, poczekaj do jutra'
    else:
        msg=None
    if request.method=="POST":
        form = AddPushup(request.POST)
        if form.is_valid():
            form.instance.user=request.user
            form.save()
            return redirect('/home')
    else:
        form = AddPushup()
    return render(request,'pushup/add_pushup.html',{'form':form,'msg':msg})

def stats_view(request):
    top5 = top5_this_week()
    top3 = top3_this_month()
    return render(request,'pushup/stats.html',{
        'top5':top5,
        'top3':top3
    })

User/views.py
from .forms import RegisterForm
from Pushup.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.shortcuts import render,get_object_or_404,redirect
from django.db.models.signals import post_save
from django.dispatch import receiver


def sign_up(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.name=form.cleaned_data.get('name')
            user.profile.surname=form.cleaned_data.get('surname')
            user.profile.age=form.cleaned_data.get('age')
            user.profile.save()
            user.save()
            login(request,user)
            return redirect('/home')
    else:
        form = RegisterForm()

    return render(request,'registration/sign_up.html',{'form':form})

@receiver(post_save,sender=User)
def update_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Pompki{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container-fluid">
        <span class="navbar-brand">Pompkowa aplikacja</span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'pushup:home' %}">Strona główna</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pushup:stats' %}">Statystyki</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pushup:add_pushup' %}">Dodaj pompki</a>
            </li>
          </ul>
            {% if user.is_authenticated %}
                <span class="me-2 text-light">Witaj {{ user }}</span>
                <a class="btn btn-danger text-light" href="{% url 'logout' %}">Wyloguj</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'user:login' %}">Zaloguj</a>
                <a class="btn btn-secondary ms-2" href="{% url 'user:register' %}">Zarejestruj</a>
            {% endif %}
        </div>
      </div>
    </nav>
    <div class="container" style="margin-top:60px">
        {% block content %}

        {% endblock %}
    </div>

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}
    Pompki
{% endblock %}

{% block content %}
    strona domowa
{% endblock %}

templates/pushup/add_pushup.html
{% extends 'base.html' %}
{% block title %}
    Dodaj pompki
{% endblock %}
{% block content %}
    {% if msg %}
    {{ msg }}
    {% else %}
        <h1>Ile pompek dzisiaj zrobiłeś?</h1>
        <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Dodaj</button>
    </form>
    {% endif %}
{% endblock %}

templates/pushup/stats.html
{% extends 'base.html' %}

{% block title %}Statystyki{% endblock %}

{% block content %}
    <h1>TOP 5 POMPKARZY W TYM TYGODNIU</h1>
    {% for record in top5 %}
        <h4>
            {{ record.user }} - Pompki: {{ record.total_count }}
        </h4>
    {% endfor %}
    <h1>TOP 3 NAJWIĘKSZEJ LICZBY SERII W OSTATNICH 30 DNIACH</h1>
    {% for record in top3 %}
        <h4>
            {{ record.user }} - Serie: {{ record.series }}
        </h4>
    {% endfor %}
{% endblock %}